title: ShoutNinja Blog
baseurl: "/blog"

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:

url: "http://shout.ninja"

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
